# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KittyKrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='save',
            name='defence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='save',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='save',
            name='next_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='save',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='save',
            name='total_health',
            field=models.IntegerField(),
        ),
    ]
