# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 02:59
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KittyKrawler', '0004_auto_20170316_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attack', models.IntegerField(null=True)),
                ('defence', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
                ('total_health', models.IntegerField(null=True)),
                ('next_level', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_save', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='save',
        ),
        migrations.AlterField(
            model_name='item',
            name='save_item',
            field=models.ManyToManyField(to='KittyKrawler.GameSave'),
        ),
        migrations.DeleteModel(
            name='Save',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='game_save',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='KittyKrawler.GameSave'),
            preserve_default=False,
        ),
    ]
