# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KittyKrawler', '0005_auto_20170316_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
