# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KittyKrawler', '0007_auto_20170324_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesave',
            old_name='save_item',
            new_name='save_items',
        ),
    ]
