# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KittyKrawler', '0008_auto_20170324_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesave',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
