# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KittyKrawler', '0010_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='kill_counter',
            field=models.IntegerField(null=True),
        ),
    ]
